(()=>{'use strict';
const $=id=>document.getElementById(id);
let ctx,buffer,source,filter,wetGain,dryGain,playing=false,currentMode='A';
const ensureAudio=()=>{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx};
function stop(){try{source?.stop()}catch{}source=null;playing=false;$('playBtn').textContent='▶ 再生'}
function buildSource(){if(!buffer)return null;const c=ensureAudio();source=c.createBufferSource();source.buffer=buffer;filter=c.createBiquadFilter();filter.type='peaking';filter.frequency.value=+$('eqFreq').value;filter.gain.value=+$('eqGain').value;filter.Q.value=+$('eqQ').value;dryGain=c.createGain();wetGain=c.createGain();source.connect(dryGain).connect(c.destination);source.connect(filter).connect(wetGain).connect(c.destination);applyAB();source.onended=stop;return source}
function play(){if(!buffer){alert('先に音源を読み込んでね');return}stop();buildSource().start();playing=true;$('playBtn').textContent='⏸ 再生中'}
function applyAB(){if(!dryGain||!wetGain)return;const t=ctx.currentTime;dryGain.gain.setTargetAtTime(currentMode==='A'?1:0,t,.01);wetGain.gain.setTargetAtTime(currentMode==='B'?1:0,t,.01)}
$('audioFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;stop();$('fileName').textContent=file.name;const data=await file.arrayBuffer();buffer=await ensureAudio().decodeAudioData(data.slice(0))};
$('playBtn').onclick=()=>playing?stop():play();$('stopBtn').onclick=stop;
const ranges=[['eqFreq','freqValue',v=>`${Math.round(v)} Hz`],['eqGain','gainValue',v=>`${Number(v)>0?'+':''}${v} dB`],['eqQ','qValue',v=>Number(v).toFixed(1)]];
const eqZones=[
 [40,80,'超低域','重さ・振動。上げすぎるとヘッドルームを消費する。'],[80,160,'低域','キックとベースの芯。濁りと迫力の境目。'],[160,350,'低中域','温かさとモコモコ感。編成が厚いと混雑しやすい。'],[350,800,'中低域','箱鳴り・こもり。削りすぎると薄くなる。'],[800,2000,'中域','音程感・前後感。ボーカルやギターの存在感。'],[2000,5000,'プレゼンス','明瞭さ・アタック・刺さり。少量の変化でも効きやすい。'],[5000,10000,'高域','明るさ・歯擦音・シンバル。耳に痛くならないよう注意。'],[10000,20000,'空気感','艶・広がり。素材に無い高域は無理に足さない。']];
function updateEQ(){const f=+$('eqFreq').value,g=+$('eqGain').value,q=+$('eqQ').value;ranges.forEach(([id,out,fmt])=>$(out).textContent=fmt($(id).value));if(filter){filter.frequency.value=f;filter.gain.value=g;filter.Q.value=q}const z=eqZones.find(x=>f>=x[0]&&f<x[1])||eqZones.at(-1);$('eqGuide').innerHTML=`<b>${z[2]}：${Math.round(f)} Hz</b><p>${z[3]}</p><p>${g>0?'ブーストで特徴を強調中。':'カットで特徴を抑制中。'} Qが高いほど狭い範囲だけを処理するよ。</p>`}
ranges.forEach(([id])=>$(id).oninput=updateEQ);$('eqReset').onclick=()=>{$('eqFreq').value=1000;$('eqGain').value=0;$('eqQ').value=1;updateEQ()};updateEQ();
const challenges=[['モコモコ',180,350],['鼻にかかった感じ',700,1300],['存在感',1800,3500],['刺さり',3000,6000],['空気感',10000,16000]];let challenge=challenges[0];function newChallenge(){challenge=challenges[Math.floor(Math.random()*challenges.length)];$('challengeText').textContent=`「${challenge[0]}」が出やすい帯域を探してみよう。`;$('challengeResult').textContent=''}$('newChallenge').onclick=newChallenge;$('checkChallenge').onclick=()=>{const f=+$('eqFreq').value;$('challengeResult').textContent=f>=challenge[1]&&f<=challenge[2]?`正解！ ${challenge[1]}〜${challenge[2]} Hz付近。`:`惜しい！目安は ${challenge[1]}〜${challenge[2]} Hz。`};
const instruments={
 vocal:{name:'🎤 ボーカル',role:'曲の主役。言葉と感情を最優先にする。',zones:'80Hz以下を整理／200〜500Hzのこもり／2〜5kHzの明瞭さ／5〜9kHzの歯擦音',chain:['クリップゲイン','EQ','コンプ','De-Esser','Delay','Reverb'],check:['小音量でも歌詞が聞こえるか','伴奏を足しても主役の位置を保てるか','補正で表情を消していないか']},
 bass:{name:'🎸 ベース',role:'低域とコード感を支え、キックとグルーヴを作る。',zones:'40〜100Hzの土台／120〜250Hzの太さ／700Hz〜2kHzの輪郭',chain:['編集','EQ','Comp','Saturation','Sidechain'],check:['小型スピーカーでも存在が分かるか','キックと同じ場所を占領していないか','音価が長すぎて濁っていないか']},
 drums:{name:'🥁 ドラム',role:'テンポ、勢い、セクションのエネルギーを作る。',zones:'キック50〜100Hz／スネア150〜250Hzと2〜5kHz／シンバル6kHz以上',chain:['Balance','EQ','Bus Comp','Transient','Room'],check:['キックとスネアが中心にいるか','オーバーヘッドの位相は自然か','ドラムバスで潰しすぎていないか']},
 guitar:{name:'🎸 ギター',role:'和音、リズム、質感を担当。ボーカルとの住み分けが重要。',zones:'100Hz以下を整理／200〜500Hzの厚み／2〜4kHzのアタック',chain:['HPF','EQ','Comp','Pan','Delay/Reverb'],check:['左右配置に意味があるか','ボーカルの明瞭帯域を邪魔していないか','歪みの高域が痛くないか']},
 keys:{name:'🎹 ピアノ・鍵盤',role:'広い音域を持つため、編成に合わせて使う範囲を決める。',zones:'低域の伴奏競合／200〜500Hzの密度／2〜5kHzの打鍵感',chain:['Arrangement','EQ','Stereo','Comp','Reverb'],check:['ベースと左手が競合していないか','ステレオ幅が広すぎないか','サスティンで濁っていないか']}
};
const ib=$('instrumentButtons');Object.entries(instruments).forEach(([k,v],i)=>{const b=document.createElement('button');b.textContent=v.name;b.dataset.key=k;if(i===0)b.classList.add('active');b.onclick=()=>showInstrument(k);ib.appendChild(b)});function showInstrument(k){const v=instruments[k];ib.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.key===k));$('instrumentDetail').innerHTML=`<h3>${v.name}</h3><p>${v.role}</p><p><b>注目帯域：</b>${v.zones}</p><div class="chain">${v.chain.map(x=>`<span>${x}</span>`).join('')}</div><ul>${v.check.map(x=>`<li>${x}</li>`).join('')}</ul>`}showInstrument('vocal');
function setAB(mode,label){currentMode=mode;applyAB();$('aBtn').classList.toggle('active',mode==='A');$('bBtn').classList.toggle('active',mode==='B');$('abStatus').textContent=label||`現在：${mode} ${mode==='A'?'原音':'EQ処理'}`}$('aBtn').onclick=()=>setAB('A');$('bBtn').onclick=()=>setAB('B');$('blindBtn').onclick=()=>{const m=Math.random()<.5?'A':'B';setAB(m,'ブラインド再生中：どちらか予想してね')};$('abMemo').value=localStorage.getItem('mix-lab-ab-memo')||'';$('saveMemo').onclick=()=>{localStorage.setItem('mix-lab-ab-memo',$('abMemo').value);$('memoSaved').textContent='保存したよ';setTimeout(()=>$('memoSaved').textContent='',1200)};
const lessons=[
 ['初級1','音量だけでバランスを作る','EQやコンプを使う前に、フェーダーだけで主役・土台・飾りの順に並べる。'],['初級2','パンニングとモノラル','左右配置を決めた後、モノラルでも主要パートが消えないか確認する。'],['初級3','EQの基本','問題帯域を探し、必要な理由がある時だけカット・ブーストする。'],['中級1','コンプレッサー','アタック、リリース、レシオで音量変化と質感を整える。'],['中級2','空間設計','リバーブとディレイをセンドで共有し、前後関係を作る。'],['中級3','キックとベース','役割帯域、音価、サイドチェインを使って低域を整理する。'],['上級1','バス処理','ドラム、楽器、ボーカルをグループ化し、まとまりと制御を作る。'],['上級2','オートメーション','固定設定では作れないセクションごとの感情変化を描く。'],['上級3','リファレンス比較','音量を合わせた完成曲と、低域・明るさ・密度・奥行きを比較する。']
];const progress=()=>JSON.parse(localStorage.getItem('mix-lab-course')||'{}');function renderCourse(){const p=progress(),done=lessons.filter(x=>p[x[0]]).length,rate=Math.round(done/lessons.length*100);$('courseProgress').innerHTML=`<b>進捗 ${done}/${lessons.length}（${rate}%）</b><div class="progress-track"><i style="width:${rate}%"></i></div>`;$('courseList').innerHTML=lessons.map(([id,title,body])=>`<details class="lesson"><summary>${p[id]?'✅':'⬜'} ${id}：${title}</summary><div class="lesson-body"><p>${body}</p><button data-lesson="${id}" class="${p[id]?'done':''}">${p[id]?'完了済み':'完了にする'}</button></div></details>`).join('');$('courseList').querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{const p=progress();p[b.dataset.lesson]=!p[b.dataset.lesson];localStorage.setItem('mix-lab-course',JSON.stringify(p));renderCourse()})}renderCourse();$('resetProgress').onclick=()=>{if(confirm('講座の進捗をリセットする？')){localStorage.removeItem('mix-lab-course');renderCourse()}};
document.querySelectorAll('.lab-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.lab-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.lab-panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${b.dataset.panel}`))});
})();