(()=>{'use strict';
const $=id=>document.getElementById(id);
const input=$('audioFile'),playBtn=$('playBtn'),stopBtn=$('stopBtn');
if(!input||!playBtn||!stopBtn)return;
let ctx,buffer,source,filter,dry,wet,master,analyser;
let playing=false,offset=0,startedAt=0,raf=0,eqBypassed=false,regionA=0,regionB=0;
const AudioCtx=window.AudioContext||window.webkitAudioContext;
const ensure=()=>{ctx=ctx||new AudioCtx();if(ctx.state==='suspended')ctx.resume();return ctx};
const fmt=s=>{s=Math.max(0,s||0);const m=Math.floor(s/60),x=Math.floor(s%60);return `${m}:${String(x).padStart(2,'0')}`};
function mount(){
 const card=document.querySelector('.upload-card'),transport=document.querySelector('.transport');
 if(!card||!transport||$('proSeek'))return;
 const pro=document.createElement('div');pro.className='pro-transport';pro.innerHTML=`<div class="seek-row"><span id="proTime" class="time-readout">0:00 / 0:00</span><input id="proSeek" type="range" min="0" max="1000" value="0" aria-label="再生位置"></div><div class="volume-row"><b>出力音量</b><input id="proVolume" type="range" min="0" max="1.5" value="1" step="0.01"><span id="proVolumeValue">100%</span></div><div class="loop-region"><b>区間ループ</b><button id="markA" type="button" class="sub">A点</button><button id="markB" type="button" class="sub">B点</button><button id="clearRegion" type="button" class="sub">解除</button><span id="regionStatus">未設定</span></div>`;card.appendChild(pro);
 const eqGrid=document.querySelector('.eq-grid');if(eqGrid){const row=document.createElement('div');row.className='eq-preset-row';row.innerHTML=`<b>EQプリセット</b><select id="eqPreset"><option value="flat">フラット</option><option value="mud">モコモコ整理</option><option value="presence">存在感アップ</option><option value="harsh">刺さり抑制</option><option value="air">空気感追加</option><option value="bass">低域整理</option></select><button id="eqBypass" type="button" class="sub">EQバイパス OFF</button>`;eqGrid.after(row)}
 const tabs=document.querySelector('.lab-tabs');if(tabs){tabs.insertAdjacentHTML('beforeend','<button data-panel="analyzer">📊 アナライザー</button><button data-panel="notes">📝 ミックスノート</button><button data-panel="quiz">🎮 耳トレ</button>')}
 const main=document.querySelector('.mix-wrap');if(main){main.insertAdjacentHTML('beforeend',`<section id="panel-analyzer" class="lab-panel"><div class="panel-head"><div><h2>リアルタイム・アナライザー</h2><p>再生中の周波数分布と波形、ピーク・平均レベルを確認できるよ。</p></div></div><div class="analyzer-wrap"><canvas id="spectrumCanvas" class="analyzer-canvas" width="1000" height="260"></canvas><canvas id="waveCanvas" class="analyzer-canvas" width="1000" height="220"></canvas><div class="meter-grid"><div class="meter-card"><b>Peak</b><span id="peakMeter">-∞ dB</span></div><div class="meter-card"><b>RMS</b><span id="rmsMeter">-∞ dB</span></div><div class="meter-card"><b>再生位置</b><span id="positionMeter">0:00</span></div></div></div></section><section id="panel-notes" class="lab-panel"><div class="panel-head"><div><h2>ミックスノート</h2><p>曲ごとの分析結果を端末に保存。音源名ごとに自動で切り替わるよ。</p></div></div><div class="mix-note-grid"><label>主役<select id="noteFocus"><option>ボーカル</option><option>ドラム</option><option>ベース</option><option>ギター</option><option>鍵盤</option><option>全体</option></select></label><label>低域<input id="noteLow" placeholder="例：少し強い、80Hzが膨らむ"></label><label>中域<input id="noteMid" placeholder="例：300Hzが混雑"></label><label>高域<input id="noteHigh" placeholder="例：4kHzが刺さる"></label><label>定位・奥行き<input id="noteSpace" placeholder="例：ボーカルが近い"></label><label class="wide">改善メモ<textarea id="noteBody" rows="7" placeholder="次に試す処理や気づきを記録"></textarea></label></div><div class="note-actions"><button id="saveMixNote" type="button">保存</button><button id="clearMixNote" type="button" class="sub">削除</button><span id="mixNoteStatus"></span></div></section><section id="panel-quiz" class="lab-panel"><div class="panel-head"><div><h2>EQ耳トレゲーム</h2><p>ランダムに強調された帯域を聴いて、どこが変化したか当てよう。</p></div><button id="newEarQuiz" type="button" class="sub">新しい問題</button></div><div class="guide-box"><b id="earQuizTitle">問題を開始してね</b><p id="earQuizHint">音源を選んで再生したあと、「新しい問題」を押してね。</p></div><div id="earQuizOptions" class="ear-quiz-options"></div><p id="earQuizResult"></p></section>`)}
 bindTabs();bindPro();loadNote();
}
function bindTabs(){document.querySelectorAll('.lab-tabs button').forEach(b=>{b.onclick=()=>{document.querySelectorAll('.lab-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.lab-panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${b.dataset.panel}`))}})}
function stop(reset=false){try{source?.stop()}catch{}source=null;playing=false;cancelAnimationFrame(raf);if(reset)offset=0;playBtn.textContent='▶ 再生';updateTime()}
function currentTime(){if(!playing)return offset;const elapsed=ctx.currentTime-startedAt;let t=offset+elapsed;const end=regionB>regionA?regionB:(buffer?.duration||0);if(end&&t>=end){if(loopOn()){t=regionB>regionA?regionA:0;offset=t;restart(t)}else{stop(true);t=0}}return t}
function loopOn(){const b=$('loopBtn');return !b||b.getAttribute('aria-pressed')!=='false'}
function restart(at){if(!buffer)return;try{source?.stop()}catch{}offset=Math.max(0,Math.min(at,buffer.duration-.01));startSource()}
function startSource(){if(!buffer)return;const c=ensure();source=c.createBufferSource();source.buffer=buffer;source.loop=loopOn();source.loopStart=regionB>regionA?regionA:0;source.loopEnd=regionB>regionA?regionB:buffer.duration;
 filter=c.createBiquadFilter();filter.type='peaking';syncEQ();dry=c.createGain();wet=c.createGain();master=c.createGain();analyser=c.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=.82;
 source.connect(dry);source.connect(filter).connect(wet);dry.connect(master);wet.connect(master);master.connect(analyser).connect(c.destination);master.gain.value=+$('proVolume').value;applyAB();source.start(0,offset);startedAt=c.currentTime;playing=true;playBtn.textContent='⏸ 一時停止';source.onended=()=>{if(!source?.loop&&!loopOn())stop(true)};draw()}
function play(){if(!buffer){alert('先に音源か内蔵練習音源を選んでね');return}if(playing){offset=currentTime();stop(false);return}startSource()}
function applyAB(){if(!dry||!wet)return;const mode=document.getElementById('bBtn')?.classList.contains('active')?'B':'A';dry.gain.value=mode==='A'?1:0;wet.gain.value=mode==='B'&&!eqBypassed?1:0;if(mode==='B'&&eqBypassed)dry.gain.value=1}
function syncEQ(){if(!filter)return;filter.frequency.value=+$('eqFreq').value;filter.gain.value=+$('eqGain').value;filter.Q.value=+$('eqQ').value}
async function loadFile(file){if(!file)return;stop(true);const data=await file.arrayBuffer();buffer=await ensure().decodeAudioData(data.slice(0));offset=0;regionA=0;regionB=0;$('fileName').textContent=file.name;updateTime();loadNote()}
function updateTime(){const duration=buffer?.duration||0,t=Math.min(currentTime(),duration);if($('proSeek'))$('proSeek').value=duration?Math.round(t/duration*1000):0;if($('proTime'))$('proTime').textContent=`${fmt(t)} / ${fmt(duration)}`;if($('positionMeter'))$('positionMeter').textContent=fmt(t)}
function bindPro(){input.onchange=e=>loadFile(e.target.files?.[0]);playBtn.onclick=play;stopBtn.onclick=()=>stop(true);
 $('proSeek').oninput=e=>{if(!buffer)return;const t=buffer.duration*(+e.target.value/1000);offset=t;if(playing)restart(t);else updateTime()};$('proVolume').oninput=e=>{const v=+e.target.value;$('proVolumeValue').textContent=`${Math.round(v*100)}%`;if(master)master.gain.value=v};
 $('markA').onclick=()=>{regionA=currentTime();$('markA').classList.add('marked');showRegion()};$('markB').onclick=()=>{regionB=currentTime();if(regionB<=regionA){regionB=0;alert('B点はA点より後ろにしてね')}else $('markB').classList.add('marked');showRegion()};$('clearRegion').onclick=()=>{regionA=regionB=0;$('markA').classList.remove('marked');$('markB').classList.remove('marked');showRegion()};
 ['eqFreq','eqGain','eqQ'].forEach(id=>$(id).addEventListener('input',syncEQ));
 $('eqPreset').onchange=e=>{const p={flat:[1000,0,1],mud:[280,-4,1.1],presence:[2800,3,1],harsh:[4200,-4,1.8],air:[12000,3,.7],bass:[90,-3,1]}[e.target.value];if(!p)return;$('eqFreq').value=p[0];$('eqGain').value=p[1];$('eqQ').value=p[2];['eqFreq','eqGain','eqQ'].forEach(id=>$(id).dispatchEvent(new Event('input',{bubbles:true})));syncEQ()};
 $('eqBypass').onclick=()=>{eqBypassed=!eqBypassed;$('eqBypass').classList.toggle('bypass-on',eqBypassed);$('eqBypass').textContent=`EQバイパス ${eqBypassed?'ON':'OFF'}`;applyAB()};
 ['aBtn','bBtn','blindBtn'].forEach(id=>$(id)?.addEventListener('click',()=>setTimeout(applyAB,0)));
 $('saveMixNote').onclick=saveNote;$('clearMixNote').onclick=clearNote;$('newEarQuiz').onclick=newQuiz;
}
function showRegion(){$('regionStatus').textContent=regionB>regionA?`${fmt(regionA)}〜${fmt(regionB)}`:regionA?`A: ${fmt(regionA)} / B未設定`:'未設定';if(playing)restart(currentTime())}
function draw(){if(!playing||!analyser)return;updateTime();drawSpectrum();drawWave();raf=requestAnimationFrame(draw)}
function drawSpectrum(){const c=$('spectrumCanvas');if(!c)return;const g=c.getContext('2d'),a=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(a);g.clearRect(0,0,c.width,c.height);g.fillStyle='#151515';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#d9c7a8';g.lineWidth=2;g.beginPath();for(let x=0;x<c.width;x++){const i=Math.floor(Math.pow(x/c.width,2)*a.length),y=c.height-(a[i]/255)*c.height;x?g.lineTo(x,y):g.moveTo(x,y)}g.stroke()}
function drawWave(){const c=$('waveCanvas');if(!c)return;const g=c.getContext('2d'),a=new Uint8Array(analyser.fftSize);analyser.getByteTimeDomainData(a);g.clearRect(0,0,c.width,c.height);g.fillStyle='#151515';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#d9c7a8';g.lineWidth=2;g.beginPath();let sum=0,peak=0;for(let i=0;i<a.length;i++){const v=(a[i]-128)/128;sum+=v*v;peak=Math.max(peak,Math.abs(v));const x=i/(a.length-1)*c.width,y=(.5+v*.42)*c.height;i?g.lineTo(x,y):g.moveTo(x,y)}g.stroke();const db=v=>v>0?20*Math.log10(v):-Infinity;$('peakMeter').textContent=Number.isFinite(db(peak))?`${db(peak).toFixed(1)} dB`:'-∞ dB';const rms=Math.sqrt(sum/a.length);$('rmsMeter').textContent=Number.isFinite(db(rms))?`${db(rms).toFixed(1)} dB`:'-∞ dB'}
function noteKey(){return `mix-lab-note:${$('fileName').textContent||'default'}`}
function saveNote(){const d={focus:$('noteFocus').value,low:$('noteLow').value,mid:$('noteMid').value,high:$('noteHigh').value,space:$('noteSpace').value,body:$('noteBody').value};localStorage.setItem(noteKey(),JSON.stringify(d));status('保存したよ')}
function loadNote(){if(!$('noteBody'))return;let d={};try{d=JSON.parse(localStorage.getItem(noteKey())||'{}')}catch{};$('noteFocus').value=d.focus||'ボーカル';$('noteLow').value=d.low||'';$('noteMid').value=d.mid||'';$('noteHigh').value=d.high||'';$('noteSpace').value=d.space||'';$('noteBody').value=d.body||''}
function clearNote(){localStorage.removeItem(noteKey());loadNote();status('削除したよ')}
function status(t){$('mixNoteStatus').textContent=t;setTimeout(()=>$('mixNoteStatus').textContent='',1300)}
const quizBands=[['低域',100],['低中域',280],['中域',1000],['プレゼンス',3200],['高域',7000],['空気感',12000]];let answer=null;
function newQuiz(){if(!buffer){alert('先に音源を選んでね');return}answer=quizBands[Math.floor(Math.random()*quizBands.length)];$('eqFreq').value=answer[1];$('eqGain').value=7;$('eqQ').value=1.4;['eqFreq','eqGain','eqQ'].forEach(id=>$(id).dispatchEvent(new Event('input',{bubbles:true})));syncEQ();document.getElementById('bBtn')?.click();$('earQuizTitle').textContent='どの帯域が強調されている？';$('earQuizHint').textContent='再生して、もっとも近い帯域を選んでね。';$('earQuizResult').textContent='';$('earQuizOptions').innerHTML=quizBands.map(([n])=>`<button type="button" data-band="${n}">${n}</button>`).join('');$('earQuizOptions').querySelectorAll('button').forEach(b=>b.onclick=()=>{const ok=b.dataset.band===answer[0];b.classList.add(ok?'correct':'wrong');$('earQuizResult').textContent=ok?`正解！ ${answer[0]}（約${answer[1]}Hz）`:`惜しい！ 正解は${answer[0]}（約${answer[1]}Hz）`;$('earQuizOptions').querySelectorAll('button').forEach(x=>x.disabled=true)})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();
})();
