// Lightweight recommended-form hero + compact root pad.
(()=>{
 const roots=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
 const rootSel=document.querySelector('#rootSelect'),typeSel=document.querySelector('#typeSelect'),bassSel=document.querySelector('#bassSelect'),controls=document.querySelector('.selection-filters'),host=document.querySelector('#selectedChord');
 if(!rootSel||!typeSel||!bassSel||!controls||!host)return;
 const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
 const score=(f,i)=>{const s=f?.shape||'';let n=100-i;if(/初心者|オープンコード|Open|簡易/.test(s))n+=80;if(/定番|CAGED|6弦ルート|5弦ルート/.test(s))n+=50;if(/PDF|資料|Bossa|Jazz|Shell|Drop2|Drop3|Voicing/.test(s))n-=10;if(/転回|Quartal|4度堆積|特殊/.test(s))n-=25;return n;};
 const badge=s=>/初心者|オープンコード|Open|簡易/.test(s)?'🔰 Easy':/Bossa/.test(s)?'🌴 Bossa':/Jazz|Shell|Drop/.test(s)?'🎷 Jazz':/PDF|資料/.test(s)?'📘 資料':'🎸 おすすめ';
 const rootPad=document.createElement('div');rootPad.className='root-note-pad';rootPad.innerHTML=`<b>ルート</b><div class="root-note-buttons">${roots.map(r=>`<button type="button" data-root="${r}">${r}</button>`).join('')}</div>`;controls.parentNode.insertBefore(rootPad,controls);
 function syncRoot(){rootPad.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.root===rootSel.value));}
 rootPad.onclick=e=>{const b=e.target.closest('[data-root]');if(!b)return;rootSel.value=b.dataset.root;rootSel.dispatchEvent(new Event('change',{bubbles:true}));syncRoot();};
 function mountHero(){if(typeof getForms!=='function')return;const forms=getForms(rootSel.value,typeSel.value,bassSel.value||'none')||[];if(!forms.length)return;let best=0,bestScore=-1e9;for(let i=0;i<forms.length;i++){const s=score(forms[i],i);if(s>bestScore){bestScore=s;best=i;}}let hero=host.querySelector('.recommended-form-hero');if(!hero){hero=document.createElement('div');hero.className='recommended-form-hero';host.prepend(hero);}const shape=forms[best]?.shape||`フォーム${best+1}`;hero.innerHTML=`<div><span>${badge(shape)}</span><b>おすすめ</b><small>${esc(shape)}</small></div><button type="button" data-index="${best}">表示</button>`;hero.querySelector('button').onclick=()=>{window.selectedFormIndex=best;if(typeof render==='function')render();};}
 [rootSel,typeSel,bassSel].forEach(el=>el.addEventListener('change',()=>requestAnimationFrame(()=>{syncRoot();mountHero();})));
 // No MutationObserver: only update when the actual selection changes.
 const st=document.createElement('style');st.textContent=`.root-note-pad{margin:0 0 8px;padding:8px 9px;border:1px solid #ded6c9;border-radius:12px;background:#fffaf2;display:flex;align-items:center;gap:8px}.root-note-pad>b{font-size:.72rem;color:#665b4f;flex:0 0 auto}.root-note-buttons{display:flex;gap:4px;overflow-x:auto;scrollbar-width:none;min-width:0}.root-note-buttons::-webkit-scrollbar{display:none}.root-note-buttons button{flex:0 0 34px;height:32px;border:1px solid #d7c9b5;border-radius:8px;background:#fff;color:#3d352d;font-weight:850;font-size:.78rem}.root-note-buttons button.active{background:#3f382f;color:#fff;border-color:#3f382f}.selection-filters label:first-child{display:none!important}.recommended-form-hero{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:0 0 8px;padding:8px 10px;border:1px solid #ded6c9;border-radius:12px;background:#fffaf2}.recommended-form-hero>div{display:grid;grid-template-columns:auto auto;gap:2px 6px;min-width:0;align-items:center}.recommended-form-hero span{font-size:.64rem;font-weight:850;color:#6b6054}.recommended-form-hero b{font-size:.82rem;color:#332b22}.recommended-form-hero small{grid-column:1/-1;color:#756a5d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:58vw}.recommended-form-hero button{border:0;border-radius:8px;background:#3f382f;color:#fff;padding:7px 9px;font-weight:800;font-size:.7rem;flex:0 0 auto}`;document.head.appendChild(st);syncRoot();requestAnimationFrame(mountHero);
})();