(()=>{
const KEY='theory-learning-v1';
const phases=[['Phase 1','基礎・コード・スケール'],['Phase 2','ジャズ・テンション・和声'],['Phase 3','作曲・旋律・編曲'],['Phase 4','ギター専門理論'],['Phase 5','耳コピ・分析・ジャンル']];
let data={done:[],fav:[]},view='all';
try{data=Object.assign(data,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){}
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const titleOf=c=>{const h=c.querySelector('h3,h2,summary,strong');return h?h.textContent.trim():''};
const itemCount=()=>typeof theoryCategories==='undefined'?0:Object.values(theoryCategories).reduce((n,c)=>n+(c.items||[]).length,0);
function init(){const guide=document.querySelector('.theory-guide');if(!guide||document.getElementById('theoryRoadmap'))return;const box=document.createElement('section');box.id='theoryRoadmap';box.className='theory-roadmap';box.innerHTML=`<div class="roadmap-head"><div><h2>📚 理論辞典 学習ダッシュボード</h2><p>読んだ項目とお気に入りを、この端末に保存できるよ。</p></div><div class="roadmap-total"><strong id="roadmapPercent">0%</strong><small id="roadmapCount"></small></div></div><div class="roadmap-progress"><span id="roadmapBar"></span></div><div class="roadmap-actions"><select id="roadmapFilter"><option value="all">すべて表示</option><option value="unread">未読だけ</option><option value="done">読んだ項目</option><option value="fav">お気に入り</option></select><button id="roadmapRandom">🎲 ランダム学習</button><button id="roadmapReset">進捗リセット</button></div><div class="roadmap-phases">${phases.map((p,i)=>`<div class="roadmap-phase${i===0?' active':''}"><b>${p[0]}</b><span>${p[1]}</span></div>`).join('')}</div>`;guide.parentNode.insertBefore(box,guide);document.getElementById('roadmapFilter').onchange=e=>{view=e.target.value;filter()};document.getElementById('roadmapRandom').onclick=random;document.getElementById('roadmapReset').onclick=()=>{data={done:[],fav:[]};save();sync()};const cards=document.getElementById('theoryCards');if(cards)new MutationObserver(decorate).observe(cards,{childList:true,subtree:true});decorate();sync()}
function decorate(){document.querySelectorAll('#theoryCards > *').forEach(card=>{const title=titleOf(card);if(!title||card.dataset.learning)return;card.dataset.learning=title;const tools=document.createElement('div');tools.className='theory-card-tools';tools.innerHTML='<button data-done>✓ 読んだ</button><button data-fav>★ お気に入り</button>';card.appendChild(tools);tools.querySelector('[data-done]').onclick=()=>toggle('done',title);tools.querySelector('[data-fav]').onclick=()=>toggle('fav',title)});sync()}
function toggle(k,t){const i=data[k].indexOf(t);i<0?data[k].push(t):data[k].splice(i,1);save();sync()}
function sync(){document.querySelectorAll('[data-learning]').forEach(card=>{const t=card.dataset.learning,d=card.querySelector('[data-done]'),f=card.querySelector('[data-fav]');if(d){d.classList.toggle('is-done',data.done.includes(t));d.textContent=data.done.includes(t)?'✓ 読了':'✓ 読んだ'}if(f){f.classList.toggle('is-favorite',data.fav.includes(t));f.textContent=data.fav.includes(t)?'★ 保存済み':'★ お気に入り'}});const total=itemCount()||1,p=Math.round(data.done.length/total*100);document.getElementById('roadmapPercent').textContent=p+'%';document.getElementById('roadmapCount').textContent=data.done.length+' / '+total;document.getElementById('roadmapBar').style.width=p+'%';filter()}
function filter(){document.querySelectorAll('[data-learning]').forEach(c=>{const t=c.dataset.learning;let show=view==='all'||view==='unread'&&!data.done.includes(t)||view==='done'&&data.done.includes(t)||view==='fav'&&data.fav.includes(t);c.classList.toggle('is-roadmap-hidden',!show)})}
function random(){view='all';document.getElementById('roadmapFilter').value='all';filter();const cards=[...document.querySelectorAll('[data-learning]')];if(!cards.length)return;const card=cards[Math.floor(Math.random()*cards.length)];card.scrollIntoView({behavior:'smooth',block:'center'});card.animate([{transform:'scale(1)'},{transform:'scale(1.025)'},{transform:'scale(1)'}],{duration:650})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();